### ISSUE TITLE
[Errno -9981] Input overflowed

### ISSUE THREAD

**Issue by Sadafaga** [swharden/Python-GUI-examples#10]
Hello,

I am actually using your python program in folder "2016-07-37_qt_audio_monitor" and I am getting the following error after a while working: "[Errno -9981] Input overflowed".

How can I fixed it? The program is running on a Raspberry Pi 3 B.

Thank you.

**Comment by jcopps** [comment]
Try: 
 self.stream.read(self.config.FRAMES_PER_BUFFER, exception_on_overflow = False)

**Comment by swharden** [comment]
Thanks for sharing this @jcopps! This should do a good job fixing @Sadafaga's issue. I'll note this technique on the readme pages.

https://github.com/swharden/Python-GUI-examples/blob/master/2016-07-37_qt_audio_monitor/README.md
